### ISSUE TITLE
Symfony 4 compatibiliy

### ISSUE THREAD

**Issue by maximilienGilet** [maximilienGilet/notification-bundle#15]
Ensure the bundle is compatible with Symfony 4

**Comment by arnoldrch** [comment]
Can't wait for this 😃

**Comment by LeandroLuccerini** [comment]
This would be very useful for my S4 project! Any update?

**Comment by maximilienGilet** [comment]
I'm working on a new sf4 project too, I don't know exactly when I will update, but soon..

Le mer. 11 avr. 2018 à 14:36, Leandro <notifications@github.com<mailto:notifications@github.com>> a écrit :

This will be very useful for my S4 project! Any update?

**Comment by maximilienGilet** [comment]
Currently working on version 3.0. 

This will bring Symfony flex/4 support along many other features and requests

Branch dev already have some commits linked. You CAN install the bundle with Symfony flex, but some things may not work and new changes are coming.

Stay tuned 😄

**Comment by mrvnklm** [comment]
Anything about the progress? If its gonna be released soon, I would wait for the release. 👍

**Comment by micayael** [comment]
I found a posible bug installing dev branch with symfony 4.1.

`There are no registered paths for namespace "MgiletNotificationBundle"`

### Posible solutions:
1. Invocations to @MgiletNotificationBundle/notifications.html.twig should be changed to @MgiletNotification/notifications.html.twig
2. Add a documentation to register a twig path for MgiletNotificationBundle

```
# twig.yaml
twig:
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/vendor/mgilet/notification-bundle/Resources/views': MgiletNotificationBundle
```

**Comment by maximilienGilet** [comment]
@micayael Thanks for testing the new version, I also found the bug.

dev branch updated with fix. It was a bad declaration of twig namespace : f5ba30b

It seems to work well now

**Comment by maximilienGilet** [comment]
New version 3.0 out ! Supports symfony flex ! (3.4 / 4.x)
