### ISSUE TITLE
How can I get my NotifiableEntity id from a NotifiableInterface?

### ISSUE THREAD

**Issue by nreynis** [maximilienGilet/notification-bundle#19]
There seems to be no convenient way to get a `NotificationEntity` id using an instance of a class implementing the `NotificationInterface`.

While it's easy to get the notifications using `mgilet_notification_render(my_entity, { 'display': 'list', 'seen': true })`,
it's really hard to use the routes `notification_mark_as_seen` and `notification_mark_all_as_seen` once you iterate over your notifications.

What is the best practice here ?

**Comment by nreynis** [comment]
Nevermind just fount the correct method, it's `notificationManager->getNotifiableEntity($notifiableInterface);`

**Comment by aquibbaig** [comment]
How to find the `notifiable entity id` from `notification` ? @nreynis

**Comment by aquibbaig** [comment]
The method is `$notificationManager->getNotifiables()`
