### ISSUE TITLE
NotificationList passed to templates should be a list of NotifiableNotification

### ISSUE THREAD

**Issue by nreynis** [maximilienGilet/notification-bundle#20]
In the template `MgiletNotificationBundle::notification_list.html.twig` the `notificationList` is an array of objects with the `seen` property and a Notification instance.
Fetching whole `NotifiableNotification` entities would not cost any performance overhead (you are already joining on the table) and provides several advantages:
* clarity, you know what you fetch
* consistency, you would have the same list in `notification_list.html.twig` and `notification.html.twig`
* routes (mark as seen, mark as unseen) would be easier to generate as you would have the `NotifiableEntity->id` at your disposal
* you are fetching an entity, not a freeform object, this means that entity could then implements `JsonSerializable` interface; that would make notifications refreshing (or lazy load) much more practical
* you could get ride of that ugly `notificationItem[0]` in your twig template and have something like `item.notification` and `item.notifiable.id`

**Comment by maximilienGilet** [comment]
Closed, implemented in #23 

Currently in branch dev. Will be merged with version 3.0 

Thanks :D
