### ISSUE TITLE
Notifications should be sorted by descending date

### ISSUE THREAD

**Issue by nreynis** [maximilienGilet/notification-bundle#25]
Notifications should be sorted by descending date by default.
Maybe you should provide a parameter in the unlikely case some users may need the oldest first.

**Comment by maximilienGilet** [comment]
Yes, this is an interesting feature !

**Comment by nico-dangerous** [comment]
Hi,
In my case, notifications are not strted at all. I saw in symfony profiler that the SQL query has no order.

```


SELECT 
  n0_.id AS id_0, 
  n0_.date AS date_1, 
  n0_.subject AS subject_2, 
  n0_.message AS message_3, 
  n0_.link AS link_4, 
  n1_.seen AS seen_5 
FROM 
  notification n0_ 
  INNER JOIN notifiable_notification n1_ ON n0_.id = n1_.notification_id 
  INNER JOIN notifiable n2_ ON n1_.notifiable_entity_id = n2_.id 
WHERE 
  n2_.identifier = ? 
  AND n2_.class = ? 
  AND n1_.seen = ?
```

This is a real problem because because I have no access to the query.

**Comment by maximilienGilet** [comment]
Notifications sorted DESC by default ! (configurable)

See commit 4347fec

**Comment by aquibbaig** [comment]
Does that work in `mgilet_notification_render()` cause this doesn't seem to work for me right now

**Comment by aquibbaig** [comment]
Fix: 
```
{{ mgilet_notification_render(app.user, 
{ 'template': './notification/notification_list.html.twig', 'order': 'DESC'}) }}
```
Here **notification_list.html.twig** is my custom template
