### ISSUE TITLE
Consider dropping `mgilet_notification_generate_path`

### ISSUE THREAD

**Issue by nreynis** [maximilienGilet/notification-bundle#26]
I don't think this helper has any added value compared to the helper already included in Symfony:
https://symfony.com/doc/current/templating.html#linking-to-pages

This is just one more thing to document and maintain and also one more thing for the user to learn which could be avoided.

**Comment by maximilienGilet** [comment]
It was intended to be an easier way to generate routes for the notifications. 

I think it would be a right to drop the helper in a 3.0 version in order to use the "Symfony way" for path generation.

**Comment by maximilienGilet** [comment]
See commit 617fbe5

**Comment by maximilienGilet** [comment]
Reverted the deletion of the method in version 3.0.1. 

After some tests and real world usage I find it really easier because it hides the bundle inner complexity.

See issue #33

**Comment by nreynis** [comment]
Wasn't the real problem in #33 that you dropped the twig helper without removing it from your templates?

Seems to me that this commit wasn't complete and some testing should have prevented the issue.

**Comment by maximilienGilet** [comment]
@nreynis You are right, I didn't notice the template usage. But in the process of fixing the template I realized the helper was clearly easier to use than the standard way of route generation. 

The helper clearly takes away the complexity of the bundle.
