### ISSUE TITLE
Add new field for entity source

### ISSUE THREAD

**Issue by YuManZz** [maximilienGilet/notification-bundle#28]
Hello,

I've started to use your bundle and I would to know if it's possible to add a field to know which entities create the notification.

For example :

On facebook each notification have a photo on left that corresponds to the entity who create the notification.

Thanks

**Comment by maximilienGilet** [comment]
Hi,

You could create an other entity like "NotifiedBy"

```php
/**
 * @ORM\Entity
 * @ORM\Table()
 * @Notifiable(name="notifiable-by")
 */
class NotifiedBy {

    /** ... */
    protected $id;

    /** ... */
    protected $myOriginalNotifiableEntity;

    /** ... */
    protected $myOtherField;

    ...
}
```

The downside is that you must create another entity on top of what you want to notify. You will have to manually create and persist a new entity each time you will create a notification.

However this solution should work for your needs.

Thank you for using the bundle

**Comment by maximilienGilet** [comment]
Closing the issue due to no response
