### ISSUE TITLE
Override Entity notification

### ISSUE THREAD

**Issue by ghoffdev** [maximilienGilet/notification-bundle#30]
Is it possible to override notification entity ? i start using your bundle and i want to map a relation between notification entity and my own entity, how can override for exemple the attribute subject in notification entity ?

**Comment by maximilienGilet** [comment]
Hi @ghoffdev ! Thanks for using my bundle.

Maybe my answer in issue #28 could be a good solution for your problem

Cheers

**Comment by ghoffdev** [comment]
My issue is not the same, i am asking if i can override the notification entity , like entity user in FOSUserBundle ?

**Comment by maximilienGilet** [comment]
It's currently not possible (version 2.x)

But it's an interesting feature to add in version 3

**Comment by Cevantime** [comment]
+1 !
Thank you for your work, by the way. @maximilienGilet

**Comment by maximilienGilet** [comment]
Feature available in 3.1 version 🎉
