### ISSUE TITLE
Unable to find template "MgiletNotificationBundle::notification_list.html.twig

### ISSUE THREAD

**Issue by ludoguenet** [maximilienGilet/notification-bundle#31]
Hello,

There is no way to make the bundle finds out the path to notification_list.html.twig 

Have you met this issue before ?

Thanks for the effort :)

**Comment by maximilienGilet** [comment]
Hi @ludoguenet,

Which version of the bundle are you using ?

Which Symfony version ?

**Comment by ludoguenet** [comment]
Hey,

I'm currently using the 2.0 version of the bundle, the Symfony version is 3.4.12

**Comment by maximilienGilet** [comment]
If you are using symfony flex I suggest you to update my bundle to the latest version (3.0)
