### ISSUE TITLE
Unknown "mgilet_notification_generate_path" function

### ISSUE THREAD

**Issue by happy-hevia** [maximilienGilet/notification-bundle#33]
Hello,

I'm trying to use the template _notification.html.twig but i got this error : 
`Unknown "mgilet_notification_generate_path" function. Did you mean "mgilet_notification_render", "mgilet_notification_unseen_count"?`
I can't find this function in your code. 

Symfony version : 4.1
NotificationBundle : 3.0

Thanks a lot

**Comment by maximilienGilet** [comment]
Hi @happy-hevia, thanks for using my bundle !

The twig function `mgilet_notification_generate_path` has been removed in the version 3 of the bundle. It wasn't really helpful. For more details about this decision, see issue #26 

Cheers

**Comment by maximilienGilet** [comment]
After some investigation I reverted the deletion of the `mgilet_notification_generate_path` function.

With version 3.0.1 it should be working fine

**Comment by happy-hevia** [comment]
It works, thanks a lot !
