### ISSUE TITLE
Issue installing/upgrading

### ISSUE THREAD

**Issue by rossvernal** [maximilienGilet/notification-bundle#34]
It might be me, and my lack of PHP experience, but when I'm upgrading from v1.0 (or dev-master as it is in the composer json file), I end up getting this from composer:
```
[ReflectionException]                                                                                                                                        
Class Mgilet\NotificationBundle\Model\AbstractNotification not found                                                                                         

[RuntimeException]                                                                                                                                           
An error occurred when executing the ""cache:clear --no-warmup"" command:                                                                                    

[Symfony\Component\Config\Exception\FileLoaderLoadException]                                                                                               
Class Mgilet\NotificationBundle\Model\AbstractNotification not found in xxxxxx\app/config\services.yml (which is being imported from xxxxxxxx\app/config\config.yml"). 
```
This seems quite specific to this package, which is why I ask - I hope you can help!

**Comment by maximilienGilet** [comment]
Hi @rossvernal !

Maybe you should remove the files of the bundle in your vendor directory and run `composer install` before clearing cache

Thanks for using the bundle

EDIT : You should consider changing the value in the `composer.json` from `dev-master` to something like `3.*`

**Comment by rossvernal** [comment]
Thanks @maximilienGilet - there seem to be a lot of links to the old AbstractNotification bits from the older versions. I'll need to unpick the old code and replace it with the new bits. No worries - thanks for the advice and taking the time to respond.
