### ISSUE TITLE
How to render "notifications.html.twig"?

### ISSUE THREAD

**Issue by arnoldrch** [maximilienGilet/notification-bundle#35]
Hi Maximilien,

I'm really struggle to render "notifications.html.twig", can you show me how to do it?

Thanks

**Comment by maximilienGilet** [comment]
Hi @arnoldrch,

What are you trying to do ? Could you provide more informations ?

**Comment by arnoldrch** [comment]
Hi Maximilien,

Thank you so much for your reply.

I want to render all notifications for a user in a page. So they can see all the notifications and do some action (mark as seen, delete etc)

Arnold

**Comment by maximilienGilet** [comment]
This is quite easy with the Twig helper provided by the bundle.

You just have to call the helper in Twig : `{{ mgilet_notification_render(notifiableEntity) }}`

To get notifications for the current user, just replace `notifiableEntity` with `app.user`.

 `{{ mgilet_notification_render(app.user) }}`

Thanks for using my bundle :) 


Documentation : https://github.com/maximilienGilet/notification-bundle/blob/master/Resources/doc/usage.rst#list-of-functions-

**Comment by MouniaAAMDI** [comment]
Hi maximilienGilet  , 
im also using your bundle, everytime i tape  {{ mgilet_notification_render(app.user) }} , the page wont refresh and gives me a server problem , can you please help ? 
Thank you so much
