### ISSUE TITLE
Error generating 'notification_mark_all_as_seen' route on an empty notificationList

### ISSUE THREAD

**Issue by KCahuete** [maximilienGilet/notification-bundle#43]
Hi Maximilien,
In the default template (vendor/mgilet/notification-bundle/Resources/views/notifications.html.twig) this error is trigerred when trying to call notificationList|first.notifiableEntity for generating 'notification_mark_all_as_seen' route : Impossible to access an attribute ("notifiableEntity") on a boolean variable ("").

**Comment by KCahuete** [comment]
I added this test to fix it on my custom template:
`{% if notificationList|length > 0 %}{% endif %}`
or
`{% if mgilet_notification_unseen_count(app.user) > 0 %}{% endif %}` in the case that I don't want to display the "mark all seen" form when there is no unseen notification

**Comment by maximilienGilet** [comment]
Hi @KCahuete , thanks for the report. 

Unfortunately I don't have time to update the bundle yet. As soon as I can I'll update it.

Cheers

**Comment by maximilienGilet** [comment]
Fixed in last commit
