### ISSUE TITLE
Seen at and type configs

### ISSUE THREAD

**Issue by curtchan** [maximilienGilet/notification-bundle#56]
I couldn't find in docs or code whether it is possible (ready to use) or doesn't require a lot of extending to:
1. set type of notification (alert, info?) to distinguish notifications with icon/font color (for example).
2. set SeenAt datetime, as of now as i understand it only saves bool whether message was marked as seen or not

**Comment by maximilienGilet** [comment]
Hi @curtchan ! Thanks for using the bundle

You can create a new entity overriding the default notification entity, as explained in the documentation :
https://github.com/maximilienGilet/notification-bundle/blob/master/Resources/doc/further.rst#override-the-notification-entity

An issue has been created if you have problems with it : #55
