### ISSUE TITLE
How to display the notifications one by one in list 

### ISSUE THREAD

**Issue by khaliltr** [maximilienGilet/notification-bundle#58]
I want to see notification list one by one not all in same row by using {{ mgilet_notification_render(notifiableEntity) }}

Please i want the code twig of this view
https://camo.githubusercontent.com/aa3ef4e798bf4d2ac1aca1e6fa048f2ea40f6360/687474703a2f2f692e696d6775722e636f6d2f30374f634636632e676966

Can you share it ??

**Comment by MouniaAAMDI** [comment]
Not the same but it will do the work
<li class="dropdown notifications-menu">
          
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">{{ mgilet_notification_count() }}</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">Vous avez {{ mgilet_notification_count() }} notifications</li>
            {#<li class="header">Vous avez#}
              {#{{ mgilet_notification_unseen_count() }}  notifications Non lus</li>#}
            <li>
              
              <ul class="menu">
                <li>
                  <a href="#">
                    <i class="fa fa-file-text-o fa-stack-1x fa-lg"></i>
                    <i class="fa fa-share fa-stack-1x stack-right-bottom text-danger"></i>
                    {#<i class="fa fa-users text-aqua"></i> #}
                    {{ mgilet_notification_render(app.user) }}
                    </a>

                  </li>
                </ul>
              </li>
              <li class="footer"><a href="#">Voir tout</a></li>
            </ul>
          </li>

**Comment by aquibbaig** [comment]
@MouniaAAMDI I can't understand anything from your comment

**Comment by aquibbaig** [comment]
@khaliltr Did you find your answer cause I am stuck here too
