### ISSUE TITLE
Security anyone?

### ISSUE THREAD

**Issue by phtmgt** [maximilienGilet/notification-bundle#59]
So, maybe it's me and I don't get it, but how do you deal with security?

I mean, the route @Route("/{notifiable}") is kinda open to everyone. Yes, you can put /notifications behind a firewall, but once you login,  you can start opening /notifications/{notifiable} however you like.

In our case, we have a User notifiable entity and the ids are easily guessable (1,2,3, etc...), so anyone who's logged in can start looking at everyone else's notifications.

I hope I am stupid and the solution is very obvious. Enlighten me, please :)

The only thing I can think of at the top of my head is just disable the /notifications route and call it a day. I doubt this will work, however (marking as seen and unseen probably will stop working).

**Comment by maximilienGilet** [comment]
Hi @plamenh !

The bundle is intended to be directly usable with a minimal setup. As you said, the provided controller is totally not secured and I encourage you to override it, adding your own security system.

For the ids, I recommend you to use a Uuid system. There is a great tutorial on how to implement it in Symfony : https://medium.com/@galopintitouan/auto-increment-is-the-devil-using-uuids-in-symfony-and-doctrine-71763721b9a9

This issue would be more like adding documentation on how to secure the usage

**Comment by p11v** [comment]
Fair enough, I just wanted to make sure I am not missing something.

Regarding the solution - should be relatively easy in my case, as the notifiable entity is my user - just check if the notifiable entity has the same id as the user. If I get around to implementing this, I will create a tutorial. For now, though, I am sticking to an API based solution and disabling the routes.

Regarding the IDs, uuid is great, but it is overhead both in terms of system and development effort. I prefer not to use IDs at all in routes open to the public.
