### ISSUE TITLE
Send a notification for all Users

### ISSUE THREAD

**Issue by KhanMaytok** [maximilienGilet/notification-bundle#6]
Is there a methos for send a notification to all users?

Actually, I do:

```
// Get all users
        $users = $this->getDoctrine()->getRepository('AppBundle:User')->findAll();

        foreach ($users as $user) {
            $manager->addNotification($user, $notification);
        }
```

But it is slow when I have many users

**Comment by maximilienGilet** [comment]
Yes, I acknowledge it might be slow. 
I'm thinking about a version 2 with a ManyToMany relation between Notification and User. This would solve performance issues and save some space in the database.

I currently don't have time to make this new version but pull requests are always welcome

**Comment by KhanMaytok** [comment]
I solved it when a traditional 

$notification = new Notification();

Then manage the users with a foreach and persist and flush aside of the foreach()  (a bulk create)
