### ISSUE TITLE
Method Not Allowed Exception on Safari

### ISSUE THREAD

**Issue by mburakergenc** [maximilienGilet/notification-bundle#7]
When marking notifications as read I'm getting a method not allowed exception. 

Here is the exact error message:
No route found for "GET /notifications/11/mark_as_seen": Method Not Allowed (Allow: POST)

Also, everything works fine on Chrome and Firefox.

**Comment by maximilienGilet** [comment]
It's totally normal here. The `/{id}/mark_as_seen` route only accept `POST` method. You should call this route only via AJAX request
