### ISSUE TITLE
Notifications list contains no html

### ISSUE THREAD

**Issue by Hnini-anass** [maximilienGilet/notification-bundle#78]
Hi, I am using this bundle, when I want to display a list of my notifications
I got
![yy](https://user-images.githubusercontent.com/68603650/88074297-1e658700-cb6f-11ea-871b-e7983fea423a.PNG)
What could cause this, and how could it be fixed?

**Comment by maximilienGilet** [comment]
Hi @Hnini-anass, if your HTML is safe you can pipe it to the `raw` twig filter

**Comment by Hnini-anass** [comment]
Already tried that, but the same result, can I try something else ?

**Comment by imphil** [comment]
This could be fixed by https://github.com/maximilienGilet/notification-bundle/pull/81?

**Comment by maximilienGilet** [comment]
thanks for the PR @imphil, it's included in the new 4.0 release. The issue should be fixed now 👍
